# Generated by Django 5.0.6 on 2024-06-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('email', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('country_of_birth', models.CharField(max_length=50)),
                ('car_id', models.BigIntegerField()),
            ],
        ),
    ]
