# Generated by Django 5.0.6 on 2024-06-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtusckerWebapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='car_id',
        ),
    ]
