# Generated by Django 5.0.6 on 2024-06-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtusckerWebapp', '0002_remove_person_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
    ]
