# Generated by Django 5.0.6 on 2024-06-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtusckerWebapp', '0004_product_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productimage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productnumber',
        ),
    ]
