# Generated by Django 5.0.6 on 2024-06-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtusckerWebapp', '0005_remove_product_productimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productdescription1',
            new_name='productdescription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productdescription2',
        ),
    ]
