# Generated by Django 5.0.6 on 2024-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtusckerWebapp', '0010_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='Description2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
