# Generated by Django 5.0.6 on 2024-07-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtusckerWebapp', '0011_product_description1_product_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
