# Generated by Django 5.0.6 on 2024-07-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtusckerWebapp', '0013_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageAlt',
        ),
    ]
