# Generated by Django 5.0.6 on 2024-07-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtusckerWebapp', '0014_remove_product_imagealt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offerFrom',
            field=models.IntegerField(null=True),
        ),
    ]
