# Generated by Django 5.0.6 on 2024-07-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtusckerWebapp', '0016_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AtusckerWebapp.categories'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
